name: 'Grafana Sync'
description: 'Sync Grafana dashboards for backing up'
author: 'SRG SRR <Pillarbox-Team@rts.ch>'
inputs:
  grafana-url:
    description: 'The URL of the Grafana instance'
    required: true
  api-key:
    description: 'Grafana API key'
    required: true
  dir:
    description: 'Directory to store dashboards'
    required: false
    default: 'dashboards'
  clear:
    description: 'Whether to clear the target directory before storing new data'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'src/index.mjs'
